version: '3'

services:
  config-service:
    image: 'config-server:latest'
    build:
      context: compaj-cloud-config
      dockerfile: Dockerfile
    container_name: config-service
    networks:
      - providers_config
    ports:
      - "8888:8888"

  discovery-service:
    image: 'discovery-service:latest'
    depends_on:
      - config-service
    networks:
      - providers_config
    build:
      context: compaj-cloud-discovery
      dockerfile: Dockerfile
    container_name: discovery-service
    hostname: discovery-service
    ports:
      - "8761:8761"

  gateway-service:
    image: 'gateway-service:latest'
    depends_on:
      - config-service
      - discovery-service
    networks:
      - providers_config
    environment:
      - TZ=Europe/Moscow
    build:
      context: compaj-cloud-gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"

  processor-service:
    image: 'processor-service:latest'
    depends_on:
      - gateway-service
    #deploy:
      #mode: replicated
      #replicas: 2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - providers_config
    environment:
      - TZ=Europe/Moscow
    build:
      context: compaj-cloud-processor
      dockerfile: Dockerfile
    expose:
      - "8081"

  user-service:
    image: 'user-service:latest'
    depends_on:
      - gateway-service
      #deploy:
      #mode: replicated
      #replicas: 2
    networks:
      - providers_config
    environment:
      - TZ=Europe/Moscow
    build:
      context: compaj-cloud-user
      dockerfile: Dockerfile
    expose:
      - "8082"

networks:
  providers_config:
    external:
      name: providers_config