version: '2'

services:
  config-server:
    image: 'config-server:latest'
    build:
      context: .
      dockerfile: ./config-server/Dockerfile
    container_name: config-server
    networks:
      - default
      - providers_config
    ports:
      - 8888:8888

  discovery-server:
    image: 'discovery-server:latest'
    depends_on:
      - config-server
    networks:
      - default
      - providers_config
    build:
      context: .
      dockerfile: ./discovery-server/Dockerfile
    container_name: discovery-server
    ports:
      - 8761:8761

networks:
  providers_config:
    external:
      name: providers_config