server:
  port: 8080
spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    bus:
      enabled: false
      id: config-service
    stream:
      kafka:
        binder:
          brokers: kafka1:19092