spring:
  application:
    name: ui-service
  cloud:
    bus:
      enabled: true
      id: config-service
    stream:
      kafka:
        binder:
          brokers: kafka1:19092

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: ui-service

server:
  port: 8081