gateway:
  discovery:
    locator:
      enabled: true
  routes:
    - id: ui-service
      uri: lb://ui-service
      predicates:
        - Path=/ui-service/**
      filters:
        - StripPrefix=1
    - id: keycloak
      uri: '${spring.security.oauth2.client.provider.base}/'
      predicates:
        - Path=/auth/realms/**
security:
  oauth2:
    client:
      base: http://localhost:8080
      provider:
        base: http://keycloak:9090
        keycloak:
          issuer-uri: '${spring.security.oauth2.client.provider.base}/auth/realms/compaj'
          authorization-uri: '${spring.security.oauth2.client.base}/auth/realms/compaj/protocol/openid-connect/auth'
          user-info-uri: '${spring.security.oauth2.client.base}/auth/realms/compaj/protocol/openid-connect/userinfo'
          user-name-attribute: preferred_username
      registration:
        keycloak-spring-gateway-client:
          provider: keycloak
          client-id: compaj-cloud-gateway
          client-secret: ifhsRmb6F2EyYubpTsPkXtiiOcPWIzf4
          authorization-grant-type: authorization_code

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    enabled: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    hostname: gateway-service